name: Tmate SSH Debug

on:  
  workflow_dispatch:  # Cho phép chạy workflow thủ công
  push:  
    branches: [ main ]  # Chạy khi có commit lên nhánh main

jobs:  
  debug:  
    runs-on: ubuntu-latest  # Chạy trên Ubuntu  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Cài đặt tmate  
        run: sudo apt-get install -y tmate  

      - name: Bắt đầu phiên SSH  
        run: tmate -F  # Mở phiên SSH, sử dụng -F để chạy foreground  

      - name: Giữ workflow chạy  
        run: sleep 1h  # Giữ workflow chạy trong 1 giờ để bạn có thời gian kết nối  
